version: 2

updates:
  # Maintain Docker dependencies.
  - package-ecosystem: docker
    assignees:
      - 'h-holm'
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'docker'

  # Maintain GitHub Actions dependencies.
  - package-ecosystem: github-actions
    assignees:
      - 'h-holm'
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'github-actions'

  # Maintain Python dependencies.
  - package-ecosystem: uv
    assignees:
      - 'h-holm'
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'python'
