ci:
  skip: [uv-ruff-lint, uv-ruff-format, uv-ty]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-docstring-first
      - id: debug-statements
      - id: check-ast
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=auto'] # Replace "auto" with "lf" to enforce Linux/Mac line endings or "crlf" for Windows

  # The built-in `check-json` hook does not support JSON5 files (~= JSON with comments and trailing commas). To lint
  # JSON5 files, use the `check-json5` hook instead.
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.1
    hooks:
      - id: check-json5

  # Ensure the `uv.lock` file is in sync with the `pyproject.toml` config.
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.18
    hooks:
      - id: uv-lock

  # Instead of using the `astral-sh/ruff-pre-commit` hook, use `uv` and the "lint" dependency group defined in the
  # `pyproject.toml`. This ensures that settings and versions between the `pre-commit` hooks and the `pyproject.toml`
  # are aligned.
  - repo: local
    hooks:
      - id: uv-ruff-lint
        name: uv ruff lint
        entry: uv run --group lint ruff check
        language: system
        types_or: [python, pyi, jupyter]
        verbose: true

  # Same reasoning as above.
  - repo: local
    hooks:
      - id: uv-ruff-format
        name: uv ruff format
        entry: uv run --group lint ruff format --check
        language: system
        types_or: [python, pyi, jupyter]
        verbose: true

  # Same reasoning as above.
  - repo: local
    hooks:
      - id: uv-ty
        name: uv ty
        entry: uv run --group lint ty check
        language: system
        types_or: [python, pyi, jupyter]
        verbose: true
