name: Deploy to Cloud Run

on:
  push:
    tags: ['**']
    branches: ['main']

concurrency:
  group: 'deploy-${{ github.workflow }}-${{ github.ref || github.run_id }}'
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  # Check which file(s) were changed, in order to decide which jobs to run.
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      application-relevant-files-changed: ${{ steps.filter.outputs.application-relevant-files }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Filter Paths
      id: filter
      uses: dorny/paths-filter@v3.0.2  # Pinned to a specific version to avoid breaking changes.
      with:
        # Detect changes to `./src` code file, unit tests, dependencies, the (building of the) container image, the
        # GitHub Actions workflows.
        filters: |
          application-relevant-files:
            - 'src/**'
            - 'tests/**/*.py'
            - 'pyproject.toml'
            - 'uv.lock'
            - 'Dockerfile'
            - '.dockerignore'
            - '.github/workflows/**'

  integration-test:
    name: Integration Test
    uses: ./.github/workflows/integration-test.yaml
    needs: [paths-filter]
    if: needs.paths-filter.outputs.application-relevant-files-changed == 'true' || startsWith(github.ref, 'refs/tags/')
    secrets: inherit
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    with:
      GITHUB_ENVIRONMENT: |-
        ${{ startsWith(github.ref, 'refs/tags') && 'prd'
         || github.ref == 'refs/heads/main' && 'prd'
         || 'stg' }}

  deploy-cloud-run-job:
    name: Deploy Cloud Run Job
    runs-on: ubuntu-latest
    needs: [paths-filter, integration-test]
    if: needs.paths-filter.outputs.application-relevant-files-changed == 'true' || startsWith(github.ref, 'refs/tags/')

    # If a commit OR tag was pushed into `main`, set the GitHub environment to "prd", else "stg".
    environment: |-
      ${{ startsWith(github.ref, 'refs/tags') && 'prd'
       || github.ref == 'refs/heads/main' && 'prd'
       || 'stg' }}

    env:
      ARTIFACT_REGISTRY_HOSTNAME: "${{ secrets.GCP_LOCATION }}-docker.pkg.dev"
      ARTIFACT_REGISTRY_URL: "${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REGISTRY_NAME }}"
      CICD_SERVICE_ACCOUNT_EMAIL: "${{ vars.GCP_CICD_SERVICE_ACCOUNT_NAME }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
      RUNTIME_SERVICE_ACCOUNT_EMAIL: "${{ vars.GCP_RUNTIME_SERVICE_ACCOUNT_NAME }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
      # Use a shorter variable name as this is referenced multiple times.
      REPO_NAME: ${{ github.event.repository.name }}

    # The `gcp-auth` step requires these permissions to read and pass tokens.
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Authenticate to Google Cloud via Workload Identity Federation (WIF).
      - name: Authenticate to Google Cloud
        id: gcp-auth
        uses: google-github-actions/auth@v3
        with:
          service_account: ${{ env.CICD_SERVICE_ACCOUNT_EMAIL }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          token_format: access_token

      # Create (or update if one already exists) a Cloud Run job. Attach a service account (SA) to the Cloud Run job
      # that has the necessary privileges for running the application logic. Note that this "runtime SA" is different
      # from the "CI/CD SA" used to run this GitHub Actions workflow. Make sure to `--execute-now` and `--wait` for the
      # job to finish, so that the CI job fails in case the job fails.
      - name: Deploy Cloud Run Job
        run: |-
          gcloud run jobs deploy "${{ env.REPO_NAME }}" \
            --image "${{ env.ARTIFACT_REGISTRY_HOSTNAME }}/${{ env.ARTIFACT_REGISTRY_URL }}/${{ env.REPO_NAME }}:sha-${{ github.sha }}" \
            --max-retries 3 \
            --task-timeout "10m" \
            --parallelism 1 \
            --region "${{ secrets.GCP_LOCATION }}" \
            --service-account "${{ env.RUNTIME_SERVICE_ACCOUNT_EMAIL }}" \
            --args="--log-level,debug,200" \
            --execute-now \
            --wait

  # If the tests and deployment jobs are successful, promote the already-pushed and now-vetted image.
  promote-image:
    name: Promote Image
    uses: ./.github/workflows/promote-image.yaml
    needs: [paths-filter, integration-test, deploy-cloud-run-job]
    if: needs.paths-filter.outputs.application-relevant-files-changed == 'true' || startsWith(github.ref, 'refs/tags/')
    secrets: inherit
    permissions:
      contents: read
      id-token: write
    with:
      GITHUB_ENVIRONMENT: |-
        ${{ startsWith(github.ref, 'refs/tags') && 'prd'
         || github.ref == 'refs/heads/main' && 'prd'
         || 'stg' }}
