name: Integration Test

on:
  # Run this workflow on any PR that is opened, reopened, or synchronized.
  pull_request:
    types: [opened, reopened, synchronize]

  # Allow this workflow to be called from other workflows.
  workflow_call:
    # To allow this re-usable workflow to read secrets from the correct GitHub environment when called from another
    # workflow, use a `workflow_call.inputs`-based approach for the setting the GitHub environment.
    inputs:
      GITHUB_ENVIRONMENT:
        description: 'The GitHub environment to use'
        type: string
        required: true
        default: ''

concurrency:
  group: 'integration-${{ github.workflow }}-${{ github.ref || github.run_id }}'
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  # Check which file(s) were changed, in order to decide which jobs to run.
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      application-relevant-files-changed: ${{ steps.filter.outputs.application-relevant-files }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Filter Paths
      id: filter
      uses: dorny/paths-filter@v3.0.2  # Pinned to a specific version to avoid breaking changes.
      with:
        # Detect changes to `./src` code file, unit tests, dependencies, the (building of the) container image, the
        # GitHub Actions workflows.
        filters: |
          application-relevant-files:
            - 'src/**'
            - 'tests/**/*.py'
            - 'pyproject.toml'
            - 'uv.lock'
            - 'Dockerfile'
            - '.dockerignore'
            - '.github/workflows/**'

  # Run the CodeQL Analysis workflow.
  codeql-analysis:
    name: CodeQL Analysis
    uses: ./.github/workflows/codeql-analysis.yaml
    needs: [paths-filter]
    if: needs.paths-filter.outputs.application-relevant-files-changed == 'true' || startsWith(github.ref, 'refs/tags/')
    permissions:
      actions: read
      contents: read
      security-events: write

  # Build and push a container image to the GCP Artifact Registry.
  build-and-push-image:
    name: Build and Push Image
    uses: ./.github/workflows/build-and-push-image.yaml
    needs: [paths-filter]
    if: needs.paths-filter.outputs.application-relevant-files-changed == 'true' || startsWith(github.ref, 'refs/tags/')
    secrets: inherit
    permissions:
      contents: read
      id-token: write

    # Secrets set in a GitHub Environment do not trickle down to re-used workflows as desired. This is a workaround to
    # make the required secrets available to the `build-and-push-image` job when calling it from here.
    with:
      GITHUB_ENVIRONMENT: |-
        ${{ startsWith(github.ref, 'refs/tags') && 'prd'
         || github.ref == 'refs/heads/main' && 'prd'
         || 'stg' }}

  integration-test:
    name: Integration Test
    needs: [paths-filter, build-and-push-image]
    if: needs.paths-filter.outputs.application-relevant-files-changed == 'true' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    # If this workflow is called from another workflow, use the `GITHUB_ENVIRONMENT` input variable. Otherwise, set the
    # GitHub Environment to "stg". This catches PRs that do not have `main` as the target branch.
    environment: ${{ inputs.GITHUB_ENVIRONMENT != '' && inputs.GITHUB_ENVIRONMENT || 'stg' }}
    env:
      ARTIFACT_REGISTRY_HOSTNAME: "${{ secrets.GCP_LOCATION }}-docker.pkg.dev"
      ARTIFACT_REGISTRY_URL: "${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REGISTRY_NAME }}"
      CICD_SERVICE_ACCOUNT_EMAIL: "${{ vars.GCP_CICD_SERVICE_ACCOUNT_NAME }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
      RUNTIME_SERVICE_ACCOUNT_EMAIL: "${{ vars.GCP_RUNTIME_SERVICE_ACCOUNT_NAME }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

    # The `gcp-auth` step requires these permissions to read and pass tokens.
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Authenticate to Google Cloud via Workload Identity Federation (WIF).
      - name: Authenticate to Google Cloud
        id: gcp-auth
        uses: google-github-actions/auth@v3
        with:
          service_account: ${{ env.CICD_SERVICE_ACCOUNT_EMAIL }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          token_format: access_token

      # Create a Cloud Run job. Make sure to `--wait` for the job to finish.
      - name: Run Cloud Run Job
        run: |-
          gcloud run jobs deploy "${{ github.event.repository.name }}-integration-test" \
            --image "${{ env.ARTIFACT_REGISTRY_HOSTNAME }}/${{ env.ARTIFACT_REGISTRY_URL }}/${{ github.event.repository.name }}:sha-${{ github.sha }}" \
            --service-account "${{ env.RUNTIME_SERVICE_ACCOUNT_EMAIL }}" \
            --max-retries 3 \
            --task-timeout 5m \
            --parallelism 1 \
            --region "${{ secrets.GCP_LOCATION }}" \
            --args="--log-level,debug,200" \
            --execute-now \
            --wait
